// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.19.4
// source: score_info.proto

// package，即包名声明符是可选的，用来防止不同的消息类型有命名冲突。
// 在没有为特定语言定义option xxx_package的时候，它还可以用来生成特定语言的包名

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 基本的积分消息
type BaseScoreInfoT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WinCount       int32    `protobuf:"varint,1,opt,name=win_count,json=winCount,proto3" json:"win_count,omitempty"`                   // 玩家胜局局数
	LoseCount      int32    `protobuf:"varint,2,opt,name=lose_count,json=loseCount,proto3" json:"lose_count,omitempty"`                // 玩家负局局数
	ExceptionCount int32    `protobuf:"varint,3,opt,name=exception_count,json=exceptionCount,proto3" json:"exception_count,omitempty"` // 玩家异常局局数
	KillCount      int32    `protobuf:"varint,4,opt,name=kill_count,json=killCount,proto3" json:"kill_count,omitempty"`                // 总人头数
	DeathCount     int32    `protobuf:"varint,5,opt,name=death_count,json=deathCount,proto3" json:"death_count,omitempty"`             // 总死亡数
	AssistCount    int32    `protobuf:"varint,6,opt,name=assist_count,json=assistCount,proto3" json:"assist_count,omitempty"`          // 总总助攻数
	Rating         int64    `protobuf:"varint,7,opt,name=rating,proto3" json:"rating,omitempty"`                                       // 评价积分
	Snippets       []string `protobuf:"bytes,8,rep,name=snippets,proto3" json:"snippets,omitempty"`                                    // 数组类型
	//*
	//Any字段允许你处理嵌套数据，并不需要它的proto定义。一个Any以bytes呈现序列化的消息，并且包含一个URL作为这个类型的唯一标
	//识和元数据。
	//为了使用Any类型，你需要引入google/protobuf/any.proto
	//Any类型用来替换proto2中的扩展。
	//
	Details []*anypb.Any `protobuf:"bytes,12,rep,name=details,proto3" json:"details,omitempty"`
	// Types that are assignable to TestOneof:
	//	*BaseScoreInfoT_M1
	//	*BaseScoreInfoT_M2
	TestOneof isBaseScoreInfoT_TestOneof `protobuf_oneof:"test_oneof"`
}

func (x *BaseScoreInfoT) Reset() {
	*x = BaseScoreInfoT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_score_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseScoreInfoT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseScoreInfoT) ProtoMessage() {}

func (x *BaseScoreInfoT) ProtoReflect() protoreflect.Message {
	mi := &file_score_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseScoreInfoT.ProtoReflect.Descriptor instead.
func (*BaseScoreInfoT) Descriptor() ([]byte, []int) {
	return file_score_info_proto_rawDescGZIP(), []int{0}
}

func (x *BaseScoreInfoT) GetWinCount() int32 {
	if x != nil {
		return x.WinCount
	}
	return 0
}

func (x *BaseScoreInfoT) GetLoseCount() int32 {
	if x != nil {
		return x.LoseCount
	}
	return 0
}

func (x *BaseScoreInfoT) GetExceptionCount() int32 {
	if x != nil {
		return x.ExceptionCount
	}
	return 0
}

func (x *BaseScoreInfoT) GetKillCount() int32 {
	if x != nil {
		return x.KillCount
	}
	return 0
}

func (x *BaseScoreInfoT) GetDeathCount() int32 {
	if x != nil {
		return x.DeathCount
	}
	return 0
}

func (x *BaseScoreInfoT) GetAssistCount() int32 {
	if x != nil {
		return x.AssistCount
	}
	return 0
}

func (x *BaseScoreInfoT) GetRating() int64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *BaseScoreInfoT) GetSnippets() []string {
	if x != nil {
		return x.Snippets
	}
	return nil
}

func (x *BaseScoreInfoT) GetDetails() []*anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

func (m *BaseScoreInfoT) GetTestOneof() isBaseScoreInfoT_TestOneof {
	if m != nil {
		return m.TestOneof
	}
	return nil
}

func (x *BaseScoreInfoT) GetM1() string {
	if x, ok := x.GetTestOneof().(*BaseScoreInfoT_M1); ok {
		return x.M1
	}
	return ""
}

func (x *BaseScoreInfoT) GetM2() int32 {
	if x, ok := x.GetTestOneof().(*BaseScoreInfoT_M2); ok {
		return x.M2
	}
	return 0
}

type isBaseScoreInfoT_TestOneof interface {
	isBaseScoreInfoT_TestOneof()
}

type BaseScoreInfoT_M1 struct {
	M1 string `protobuf:"bytes,13,opt,name=m1,proto3,oneof"`
}

type BaseScoreInfoT_M2 struct {
	M2 int32 `protobuf:"varint,14,opt,name=m2,proto3,oneof"`
}

func (*BaseScoreInfoT_M1) isBaseScoreInfoT_TestOneof() {}

func (*BaseScoreInfoT_M2) isBaseScoreInfoT_TestOneof() {}

var File_score_info_proto protoreflect.FileDescriptor

var file_score_info_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0c, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x03,
	0x0a, 0x11, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x5f, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x77, 0x69, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x27, 0x0a, 0x0f, 0x65, 0x78, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x65, 0x78, 0x63, 0x65, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6b, 0x69, 0x6c, 0x6c,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6b, 0x69,
	0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x61, 0x74, 0x68,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x65,
	0x61, 0x74, 0x68, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x73, 0x73, 0x69,
	0x73, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6e, 0x69, 0x70, 0x70, 0x65, 0x74, 0x73, 0x18,
	0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6e, 0x69, 0x70, 0x70, 0x65, 0x74, 0x73, 0x12,
	0x2e, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12,
	0x10, 0x0a, 0x02, 0x6d, 0x31, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x6d,
	0x31, 0x12, 0x10, 0x0a, 0x02, 0x6d, 0x32, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52,
	0x02, 0x6d, 0x32, 0x42, 0x0c, 0x0a, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6f, 0x6e, 0x65, 0x6f,
	0x66, 0x4a, 0x04, 0x08, 0x0f, 0x10, 0x10, 0x4a, 0x04, 0x08, 0x09, 0x10, 0x0c, 0x52, 0x03, 0x66,
	0x6f, 0x6f, 0x52, 0x03, 0x62, 0x61, 0x72, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_score_info_proto_rawDescOnce sync.Once
	file_score_info_proto_rawDescData = file_score_info_proto_rawDesc
)

func file_score_info_proto_rawDescGZIP() []byte {
	file_score_info_proto_rawDescOnce.Do(func() {
		file_score_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_score_info_proto_rawDescData)
	})
	return file_score_info_proto_rawDescData
}

var file_score_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_score_info_proto_goTypes = []interface{}{
	(*BaseScoreInfoT)(nil), // 0: score_server.base_score_info_t
	(*anypb.Any)(nil),      // 1: google.protobuf.Any
}
var file_score_info_proto_depIdxs = []int32{
	1, // 0: score_server.base_score_info_t.details:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_score_info_proto_init() }
func file_score_info_proto_init() {
	if File_score_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_score_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseScoreInfoT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_score_info_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*BaseScoreInfoT_M1)(nil),
		(*BaseScoreInfoT_M2)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_score_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_score_info_proto_goTypes,
		DependencyIndexes: file_score_info_proto_depIdxs,
		MessageInfos:      file_score_info_proto_msgTypes,
	}.Build()
	File_score_info_proto = out.File
	file_score_info_proto_rawDesc = nil
	file_score_info_proto_goTypes = nil
	file_score_info_proto_depIdxs = nil
}
